builds:
  - id: "redis-web-manager"
    binary: RWM
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "docker.io/slowrookie/redis-web-manager:{{ .Tag }}"
      - "gcr.io/slowrookie/redis-web-manager:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile