builds:
  - id: "redis-web-manager"
    binary: RWM
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "slowrookie/redis-web-manager:{{ .Tag }}"
    dockerfile: Dockerfile