builds:
  - id: "redis-web-manager"
    binary: RWM
    ldflags:
      - -s -w 
      - -X github.com/kleveross/ormb/pkg/version.VERSION={{ .Version }} 
      - -X github.com/kleveross/ormb/pkg/version.COMMIT={{ .Commit }}
      - -X github.com/kleveross/ormb/pkg/version.REPOROOT={{ .GitURL }}
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "docker.io/slowrookie/redis-web-manager:{{ .Tag }}"
      - "gcr.io/slowrookie/redis-web-manager:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile